[staffchat]
  enabled = true
  name = "staffchat"
  aliases = [
    "sc",
    "schat"
  ]
  description = "Chat with other staff members"

[report]
  enabled = true
  name = "report"
  aliases = []
  description = "Report a player"