# All in-game messages are formatted using MiniMessage
# You can use the MiniMessage Viewer to preview and format your messages:
# https://webui.advntr.dev

# The message sent to players when they don't have permission to execute a command
permission_message = "<red>You don't have permission to execute this command</red>"

[staffchat]

  # The message shown to in-game staff when using the staffchat command on a Paper or Spigot server
  # Placeholders:
  # <displayname> - The player's displayname
  # <username> - The player's username
  # <message> - The sent message
  server_from_server = "<red>StaffChat <yellow><username></yellow>:</red> <green><message></green>"

  # The message shown to in-game staff when using the staffchat command on a proxy server (Velocity/BungeeCord)
  # Placeholders:
  # <username> - The player's username
  # <server> - The server the player is connected to
  # <message> - The sent message
  proxy_from_proxy = "<red>StaffChat <yellow><username></yellow> <gold>(<server>)</gold>:</red> <green><message></green>"

  # The message shown to in-game staff when receiving a message from Discord
  # Placeholders:
  # <profile> - The user's (nick)name with extra info when hovering over their name
  # <displayname> - The user's (nick)name in the current server
  # <username> - The user's username
  # <message> - The sent message
  game_from_discord = "<blue>Discord</blue> <red>StaffChat <yellow><profile></yellow>:</red> <green><message></green>"

  # The message shown in Discord when using the staffchat command on a Paper or Spigot server
  # Placeholders:
  # <displayname> - The player's displayname
  # <username> - The player's username
  # <message> - The sent message
  discord_from_server = "**[StaffChat] <username>**: <message>"

  # The message shown in Discord when using the staffchat command on a proxy server (Velocity/BungeeCord)
  # Placeholders:
  # <username> - The player's username
  # <server> - The server the player is connected to
  # <message> - The sent message
  discord_from_proxy = "**[StaffChat] <username> (<server>)**: <message>"